
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/iSeen/ZNSpecs.git'

use_frameworks!

target 'ZNPods_Example' do
  pod 'ZNPods', :path => '../'

  target 'ZNPods_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
